// Branded "Brève du jour" social card. 1200×630 PNG generated by
// @vercel/og (Satori). Cached 5 min so FB scraper bursts don't hammer
// the DB.
//
// Two layouts, picked automatically:
//   MATCH MODE  — when an AB fixture kicks off within the next 7 days,
//                 show AB vs OPP, countdown, kickoff, venue, broadcast.
//                 Functions as an event poster on social feeds.
//   DIGEST MODE — fallback identity card with date + article count.
import type { APIRoute } from 'astro';
import { ImageResponse } from '@vercel/og';
import { listArticles, getNextFixture } from '~/lib/data';

export const prerender = false;

const CIEL   = '#B3DCFA';
const NIGHT  = '#0B2545';
const FG     = '#1A1D24';
const MUTED  = '#5F6975';
const AVIRON = '#006B9D';

const PARIS = 'Europe/Paris';
const fmtDate = new Intl.DateTimeFormat('fr-FR', {
  weekday: 'long', day: 'numeric', month: 'long', timeZone: PARIS,
});
const fmtTime = new Intl.DateTimeFormat('fr-FR', {
  hour: '2-digit', minute: '2-digit', timeZone: PARIS,
});

export const GET: APIRoute = async () => {
  const [articles, fixture] = await Promise.all([
    listArticles({ since: 'today', limit: 50 }),
    getNextFixture(),
  ]);

  const today = fmtDate.format(new Date());
  const articleCount = articles.length;

  // Match mode triggers when the next fixture is within the next 7 days.
  const matchMode = fixture
    && new Date(fixture.kickoff).getTime() - Date.now() <= 7 * 86_400_000;

  const card = matchMode
    ? renderMatchMode(fixture, articleCount, today)
    : renderDigestMode(articleCount, today);

  return new ImageResponse(card as never, {
    width: 1200,
    height: 630,
    headers: { 'cache-control': 'public, max-age=300, s-maxage=300' },
  });
};

// ── Layout helpers ────────────────────────────────────────────────────────
// Both layouts share the brand band + footer; only the middle changes.

function brandBand(rightSlot: string) {
  return {
    type: 'div',
    props: {
      style: {
        background: CIEL,
        padding: '32px 60px 26px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      children: [
        {
          type: 'div',
          props: {
            style: {
              fontFamily: 'serif',
              fontSize: '40px',
              fontWeight: 700,
              color: NIGHT,
              letterSpacing: '-1.2px',
              lineHeight: 1,
            },
            children: 'AUPA AB',
          },
        },
        {
          type: 'div',
          props: {
            style: {
              fontSize: '15px',
              fontWeight: 700,
              color: NIGHT,
              opacity: 0.7,
              letterSpacing: '2.5px',
              textTransform: 'uppercase',
            },
            children: rightSlot,
          },
        },
      ],
    },
  };
}

function footer(leftText: string) {
  return {
    type: 'div',
    props: {
      style: {
        padding: '20px 60px 28px',
        borderTop: '1px solid #E5E2D9',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        fontSize: '20px',
        color: MUTED,
      },
      children: [
        { type: 'span', props: { children: leftText } },
        {
          type: 'span',
          props: {
            style: {
              color: AVIRON,
              fontWeight: 700,
              fontSize: '18px',
              letterSpacing: '1px',
              textTransform: 'uppercase',
            },
            children: 'aupaab.fr',
          },
        },
      ],
    },
  };
}

// ── DIGEST MODE (no match in the next week) ──────────────────────────────
function renderDigestMode(count: number, today: string) {
  return {
    type: 'div',
    props: {
      style: {
        width: '1200px',
        height: '630px',
        display: 'flex',
        flexDirection: 'column',
        background: '#FAFAF7',
      },
      children: [
        brandBand(`Brève du ${today}`),
        {
          type: 'div',
          props: {
            style: {
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              padding: '20px 60px',
              textAlign: 'center',
            },
            children: [
              {
                type: 'div',
                props: {
                  style: {
                    fontFamily: 'serif',
                    fontSize: '92px',
                    fontWeight: 700,
                    color: FG,
                    letterSpacing: '-3px',
                    lineHeight: 1,
                  },
                  children: 'La brève du jour',
                },
              },
              {
                type: 'div',
                props: {
                  style: {
                    marginTop: '32px',
                    fontSize: '26px',
                    color: MUTED,
                    letterSpacing: '0.5px',
                  },
                  children: count > 0
                    ? `${count} article${count > 1 ? 's' : ''} AB synthétisé${count > 1 ? 's' : ''} dans les dernières 24 h`
                    : 'Toute l\'actu de l\'Aviron Bayonnais',
                },
              },
            ],
          },
        },
        footer(today.charAt(0).toUpperCase() + today.slice(1)),
      ],
    },
  };
}

// ── MATCH MODE (fixture within 7 days) ───────────────────────────────────
function renderMatchMode(fixture: NonNullable<Awaited<ReturnType<typeof getNextFixture>>>, count: number, today: string) {
  const kickoff = new Date(fixture.kickoff);
  const day = fmtDate.format(kickoff);
  const time = fmtTime.format(kickoff).replace(':', 'h');
  const opponent = fixture.is_home ? fixture.away_short : fixture.home_short;
  const opponentName = fixture.is_home ? fixture.away_name : fixture.home_name;
  const venue = fixture.venue || (fixture.is_home ? 'Stade Jean-Dauger' : '');
  const diffDays = Math.ceil((kickoff.getTime() - Date.now()) / 86_400_000);
  const countdown = diffDays <= 0 ? 'AUJOURD\'HUI'
                  : diffDays === 1 ? 'DEMAIN'
                  : `J−${diffDays}`;

  const leftTeam = fixture.is_home ? 'BAY' : opponent;
  const rightTeam = fixture.is_home ? opponent : 'BAY';
  const leftLong = fixture.is_home ? 'Aviron Bayonnais' : opponentName;
  const rightLong = fixture.is_home ? opponentName : 'Aviron Bayonnais';

  return {
    type: 'div',
    props: {
      style: {
        width: '1200px',
        height: '630px',
        display: 'flex',
        flexDirection: 'column',
        background: '#FAFAF7',
      },
      children: [
        brandBand(`Prochain match · ${countdown}`),
        // Match block
        {
          type: 'div',
          props: {
            style: {
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              padding: '24px 60px',
            },
            children: [
              // Teams row
              {
                type: 'div',
                props: {
                  style: {
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '60px',
                    marginBottom: '24px',
                  },
                  children: [
                    {
                      type: 'div',
                      props: {
                        style: { display: 'flex', flexDirection: 'column', alignItems: 'center', width: '380px' },
                        children: [
                          {
                            type: 'div',
                            props: {
                              style: {
                                fontFamily: 'serif',
                                fontSize: '110px',
                                fontWeight: 700,
                                color: FG,
                                letterSpacing: '-4px',
                                lineHeight: 1,
                              },
                              children: leftTeam,
                            },
                          },
                          {
                            type: 'div',
                            props: {
                              style: { marginTop: '8px', fontSize: '18px', color: MUTED, textAlign: 'center' },
                              children: leftLong,
                            },
                          },
                        ],
                      },
                    },
                    {
                      type: 'div',
                      props: {
                        style: {
                          fontFamily: 'serif',
                          fontSize: '52px',
                          fontWeight: 400,
                          color: MUTED,
                          fontStyle: 'italic',
                        },
                        children: 'vs',
                      },
                    },
                    {
                      type: 'div',
                      props: {
                        style: { display: 'flex', flexDirection: 'column', alignItems: 'center', width: '380px' },
                        children: [
                          {
                            type: 'div',
                            props: {
                              style: {
                                fontFamily: 'serif',
                                fontSize: '110px',
                                fontWeight: 700,
                                color: FG,
                                letterSpacing: '-4px',
                                lineHeight: 1,
                              },
                              children: rightTeam,
                            },
                          },
                          {
                            type: 'div',
                            props: {
                              style: { marginTop: '8px', fontSize: '18px', color: MUTED, textAlign: 'center' },
                              children: rightLong,
                            },
                          },
                        ],
                      },
                    },
                  ],
                },
              },
              // Meta row (kickoff + venue + broadcast)
              {
                type: 'div',
                props: {
                  style: {
                    display: 'flex',
                    justifyContent: 'center',
                    gap: '24px',
                    fontSize: '22px',
                    color: FG,
                    marginTop: '12px',
                  },
                  children: [
                    { type: 'span', props: { style: { fontWeight: 600 }, children: `${day} · ${time}` } },
                    { type: 'span', props: { style: { color: MUTED }, children: '·' } },
                    { type: 'span', props: { children: venue } },
                    ...(fixture.broadcast ? [
                      { type: 'span', props: { style: { color: MUTED }, children: '·' } },
                      { type: 'span', props: { style: { color: AVIRON, fontWeight: 600 }, children: fixture.broadcast } },
                    ] : []),
                  ],
                },
              },
            ],
          },
        },
        footer(`${count} article${count > 1 ? 's' : ''} AB aujourd'hui`),
      ],
    },
  };
}
