// Branded "Brève du jour" social card.
//
// 1200×630 PNG generated by @vercel/og (Satori under the hood). Cached
// 5 min to absorb the burst when FB scrapes after our cron post.
//
// Layout: sky-blue brand band at top with "AUPA AB" + dateline kicker,
// big serif headline with the first article's ai_title, footer with
// "+ N autres articles" + aupaab.fr.

import type { APIRoute } from 'astro';
import { ImageResponse } from '@vercel/og';
import { listArticles } from '~/lib/data';

export const prerender = false;

const CIEL = '#B3DCFA';
const FG = '#1A1D24';
const MUTED = '#5F6975';
const AVIRON = '#006B9D';

export const GET: APIRoute = async () => {
  const articles = await listArticles({ limit: 5 });
  const first = articles[0];
  const remaining = Math.max(0, articles.length - 1);

  const dateLabel = new Intl.DateTimeFormat('fr-FR', {
    weekday: 'long', day: 'numeric', month: 'long',
    timeZone: 'Europe/Paris',
  }).format(new Date());

  const headline = first?.ai_title ?? first?.title ?? "L'actu de l'Aviron Bayonnais";
  const countLabel = remaining > 0
    ? `+ ${remaining} autre${remaining > 1 ? 's' : ''} article${remaining > 1 ? 's' : ''} aujourd'hui`
    : 'Pas d\'autre actu aujourd\'hui';

  // Satori uses a subset of CSS Flexbox + a strict typography model. No
  // 'system-ui' shortcut — we list real fallbacks Satori bundles.
  const card = {
    type: 'div',
    props: {
      style: {
        width: '1200px',
        height: '630px',
        display: 'flex',
        flexDirection: 'column',
        background: '#FAFAF7',
      },
      children: [
        // Brand band
        {
          type: 'div',
          props: {
            style: {
              background: CIEL,
              padding: '36px 60px 30px',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-start',
            },
            children: [
              {
                type: 'div',
                props: {
                  style: {
                    fontFamily: 'serif',
                    fontSize: '52px',
                    fontWeight: 700,
                    color: '#FFFFFF',
                    letterSpacing: '-2px',
                    lineHeight: 1,
                  },
                  children: 'AUPA AB',
                },
              },
              {
                type: 'div',
                props: {
                  style: {
                    marginTop: '8px',
                    fontSize: '15px',
                    fontWeight: 600,
                    color: '#FFFFFF',
                    opacity: 0.92,
                    letterSpacing: '4px',
                    textTransform: 'uppercase',
                  },
                  children: `Brève du ${dateLabel}`,
                },
              },
            ],
          },
        },
        // Body
        {
          type: 'div',
          props: {
            style: {
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              padding: '48px 60px 24px',
            },
            children: [
              {
                type: 'div',
                props: {
                  style: {
                    fontFamily: 'serif',
                    fontSize: '60px',
                    fontWeight: 700,
                    color: FG,
                    lineHeight: 1.08,
                    letterSpacing: '-2px',
                    // soft-clamp via overflow hidden + max height
                    display: '-webkit-box',
                    overflow: 'hidden',
                    maxHeight: '300px',
                  },
                  children: headline,
                },
              },
              {
                type: 'div',
                props: {
                  style: {
                    marginTop: 'auto',
                    paddingTop: '24px',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'baseline',
                    fontSize: '22px',
                    color: MUTED,
                  },
                  children: [
                    { type: 'span', props: { children: countLabel } },
                    {
                      type: 'span',
                      props: {
                        style: { color: AVIRON, fontWeight: 600 },
                        children: 'aupaab.fr',
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  };

  return new ImageResponse(card as never, {
    width: 1200,
    height: 630,
    headers: {
      'cache-control': 'public, max-age=300, s-maxage=300',
    },
  });
};
