// Branded "Brève du jour" social card.
//
// 1200×630 PNG generated by @vercel/og (Satori under the hood). Cached
// 5 min to absorb the burst when FB scrapes after our cron post.
//
// Layout: sky-blue brand band at top, navy text (AAA contrast), big
// headline with the day's lead story, count of other articles, hostname.

import type { APIRoute } from 'astro';
import { ImageResponse } from '@vercel/og';
import { listArticles } from '~/lib/data';

export const prerender = false;

const CIEL  = '#B3DCFA';
const NIGHT = '#0B2545';
const FG    = '#1A1D24';
const MUTED = '#5F6975';
const AVIRON = '#006B9D';

export const GET: APIRoute = async () => {
  // Match post-fb.mjs's window (last 24h) so the count stays in sync.
  const articles = await listArticles({ since: 'today', limit: 50 });
  const first = articles[0];
  const remaining = Math.max(0, articles.length - 1);

  const dateLabel = new Intl.DateTimeFormat('fr-FR', {
    weekday: 'long', day: 'numeric', month: 'long',
    timeZone: 'Europe/Paris',
  }).format(new Date());

  const headline = first?.ai_title ?? first?.title ?? "L'actu de l'Aviron Bayonnais";
  const countLabel = remaining > 0
    ? `+ ${remaining} autre${remaining > 1 ? 's' : ''} article${remaining > 1 ? 's' : ''} aujourd'hui`
    : null;

  // Satori object-tree. No JSX → no React dep, no transform pipeline.
  const card = {
    type: 'div',
    props: {
      style: {
        width: '1200px',
        height: '630px',
        display: 'flex',
        flexDirection: 'column',
        background: '#FAFAF7',
      },
      children: [
        // Brand band — ciel bg + navy text for AAA contrast (~9:1)
        {
          type: 'div',
          props: {
            style: {
              background: CIEL,
              padding: '32px 60px 26px',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'space-between',
            },
            children: [
              {
                type: 'div',
                props: {
                  style: { display: 'flex', flexDirection: 'column' },
                  children: [
                    {
                      type: 'div',
                      props: {
                        style: {
                          fontFamily: 'serif',
                          fontSize: '46px',
                          fontWeight: 700,
                          color: NIGHT,
                          letterSpacing: '-1.5px',
                          lineHeight: 1,
                        },
                        children: 'AUPA AB',
                      },
                    },
                    {
                      type: 'div',
                      props: {
                        style: {
                          marginTop: '8px',
                          fontSize: '15px',
                          fontWeight: 600,
                          color: NIGHT,
                          opacity: 0.7,
                          letterSpacing: '3px',
                          textTransform: 'uppercase',
                        },
                        children: `La brève du ${dateLabel}`,
                      },
                    },
                  ],
                },
              },
              // Right-side mini badge: hostname
              {
                type: 'div',
                props: {
                  style: {
                    fontSize: '17px',
                    fontWeight: 700,
                    color: NIGHT,
                    opacity: 0.65,
                    letterSpacing: '1px',
                  },
                  children: 'aupaab.fr',
                },
              },
            ],
          },
        },
        // Body — big headline centred vertically in the remaining space
        {
          type: 'div',
          props: {
            style: {
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              padding: '60px 60px 36px',
              justifyContent: 'space-between',
            },
            children: [
              {
                type: 'div',
                props: {
                  style: {
                    fontFamily: 'serif',
                    fontSize: '64px',
                    fontWeight: 700,
                    color: FG,
                    lineHeight: 1.06,
                    letterSpacing: '-2px',
                    display: 'flex',
                  },
                  children: headline,
                },
              },
              // Footer line: count of other articles + a chevron
              {
                type: 'div',
                props: {
                  style: {
                    marginTop: '24px',
                    paddingTop: '24px',
                    borderTop: '1px solid #E5E2D9',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'baseline',
                    fontSize: '20px',
                    color: MUTED,
                  },
                  children: [
                    {
                      type: 'span',
                      props: {
                        children: countLabel ?? 'Toute l\'actu AB, en quelques mots',
                      },
                    },
                    {
                      type: 'span',
                      props: {
                        style: { color: AVIRON, fontWeight: 700, fontSize: '18px', letterSpacing: '1px', textTransform: 'uppercase' },
                        children: 'lire →',
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  };

  return new ImageResponse(card as never, {
    width: 1200,
    height: 630,
    headers: {
      // Browser cache 5 min, CDN cache 5 min — keeps the day's card fresh
      // without battering the DB on FB scraper bursts.
      'cache-control': 'public, max-age=300, s-maxage=300',
    },
  });
};
