// AUPA AB — fictional but in-character editorial data
// Aviron Bayonnais 2025-26 season, Top 14

window.AUPA_DATA = (() => {
  const sources = {
    'sud-ouest': { name: 'Sud Ouest', mono: 'SO', color: '#C8102E' },
    'la-rep':    { name: 'La République des Pyrénées', mono: 'LR', color: '#1B5E20' },
    'rmc':       { name: 'RMC Sport', mono: 'RMC', color: '#003F87' },
    'midol':     { name: 'Midi Olympique', mono: 'MO', color: '#7B1FA2' },
    'lequipe':   { name: "L'Équipe", mono: 'EQ', color: '#1A1A1A' },
    'rugbyrama': { name: 'Rugbyrama', mono: 'RR', color: '#0288D1' },
    'aupa':      { name: 'AUPA AB', mono: 'AB', color: '#0099D8' },
  };

  const nextMatch = {
    home: { name: 'Aviron Bayonnais', short: 'AB', form: ['V', 'D', 'V', 'V', 'N'] },
    away: { name: 'Stade Toulousain',  short: 'ST', form: ['V', 'V', 'V', 'D', 'V'] },
    venue: 'Stade Jean-Dauger',
    kickoff: 'Samedi 17 mai · 21h05',
    competition: 'Top 14 · J24',
    diffusion: 'Canal+ Sport',
    daysOut: 3,
    hoursOut: 2,
    minsOut: 14,
  };

  const articles = [
    {
      id: 'maka-prolonge',
      slug: 'edwin-maka-prolonge-deux-saisons',
      category: 'Mercato',
      source: 'sud-ouest',
      author: 'Pierre Lasserre',
      time: 'il y a 1 h',
      date: '14 mai 2026',
      readingMin: 4,
      title: 'Edwin Maka prolonge deux saisons : « Bayonne, c\u2019est devenu chez moi (le piment d\u2019Espelette aussi) »',
      lede: 'Le troisième-ligne fidjien, arrivé en 2022, a paraphé un nouveau contrat jusqu\u2019en 2028. Le club tient l\u2019un de ses cadres, à un moment où le marché s\u2019affole.',
      body: [
        'Il y a des signatures qui font du bruit, et il y a des signatures qui en disent long. Celle d\u2019Edwin Maka, finalisée mardi en fin d\u2019après-midi dans les bureaux de la rue des Allées Paulmy, appartient à la seconde catégorie. Le troisième-ligne fidjien de 30 ans s\u2019engage avec l\u2019Aviron Bayonnais jusqu\u2019au 30 juin 2028.',
        '« On en discutait depuis février », confirme le directeur sportif Jean-Baptiste Aldigé. « Edwin était attendu ailleurs — on ne va pas se mentir, deux clubs anglais étaient passés à l\u2019offensive. Mais il y avait une volonté commune de continuer, et ça simplifie beaucoup de choses ».',
        'Sur le terrain, l\u2019ailier de la troisième-ligne ciel et blanc affiche cette saison son meilleur ratio plaquages-courses (89 % de réussite, 14 turnovers gagnés). Hors du terrain, le bonhomme s\u2019est intégré au point d\u2019envoyer ses enfants à l\u2019école bilingue d\u2019Anglet. C\u2019est ce genre de détails qui pèsent, parfois plus que les zéros sur le contrat.',
        'Il y a aussi, quelque part, l\u2019aveu d\u2019un projet sportif. Quand un joueur de ce calibre, sollicité ailleurs, choisit de rester dans un club qui a connu le purgatoire de la Pro D2 il y a quatre saisons, c\u2019est qu\u2019il croit à quelque chose. Reste à voir ce que ça donne en mai prochain.',
      ],
      tags: ['Mercato', 'Edwin Maka', 'Prolongation', 'Top 14'],
      comments: 28,
      featured: true,
    },
    {
      id: 'avant-match-toulouse',
      category: 'Avant-match',
      source: 'aupa',
      author: 'La rédaction AUPA',
      time: 'il y a 3 h',
      date: '14 mai 2026',
      readingMin: 6,
      title: 'Avant-match Bayonne — Toulouse : et si, cette fois, on osait y croire ?',
      lede: 'Samedi, à Jean-Dauger, l\u2019AB reçoit le champion de France en titre. Sept ans qu\u2019on n\u2019avait pas battu ces gens-là à la maison. Sept. Ans. Mais.',
      tags: ['Top 14', 'Toulouse', 'Jean-Dauger'],
      comments: 47,
      lead: true,
    },
    {
      id: 'lopez-vintage',
      category: 'Coulisses',
      source: 'rmc',
      author: 'Mathieu Lartot',
      time: 'il y a 5 h',
      date: '14 mai 2026',
      readingMin: 3,
      title: 'Camille Lopez : « Je ne suis pas vieux, je suis vintage »',
      lede: 'À 36 ans, l\u2019ouvreur basque est interrogé sur sa fin de carrière. Réponse en forme de pirouette, en plein milieu d\u2019une conférence de presse qui partait sur autre chose.',
      tags: ['Camille Lopez', 'Coulisses'],
      comments: 53,
    },
    {
      id: 'rumeurs-classement',
      category: 'Mercato',
      source: 'midol',
      author: 'Léo Faure',
      time: 'il y a 7 h',
      date: '14 mai 2026',
      readingMin: 5,
      title: 'Mercato : les rumeurs de fin de saison, classées de « sérieuse » à « franchement délirante »',
      lede: 'On a passé les bruits de couloir au filtre. Spedding à Bayonne ? Sérieux. Beauden Barrett à Jean-Dauger ? Plus tendu. Notre tri.',
      tags: ['Mercato', 'Rumeurs'],
      comments: 92,
    },
    {
      id: 'la-rochelle-bilan',
      category: 'Après-match',
      source: 'la-rep',
      author: 'Iban Etcheverry',
      time: 'il y a 9 h',
      date: '13 mai 2026',
      readingMin: 4,
      title: 'Mêlée fermée : ce qui s\u2019est dit dans le vestiaire après La Rochelle',
      lede: 'Défaite frustrante, indiscipline qui revient, capitaine remonté. On a reconstitué l\u2019heure qui a suivi le coup de sifflet final.',
      tags: ['La Rochelle', 'Vestiaire'],
      comments: 31,
    },
    {
      id: 'jean-dauger-travaux',
      category: 'Club',
      source: 'sud-ouest',
      author: 'Florence Mounet',
      time: 'hier',
      date: '13 mai 2026',
      readingMin: 3,
      title: 'Jean-Dauger : la tribune Sud refaite à l\u2019intersaison, les abonnés relogés (sans drame)',
      lede: 'Travaux confirmés. 12 000 places concernées pendant six semaines. Le club a anticipé le casse-tête.',
      tags: ['Stade', 'Travaux'],
      comments: 14,
    },
    {
      id: 'crabos-titre',
      category: 'Formation',
      source: 'la-rep',
      author: 'Jean-Marc Larrieu',
      time: 'hier',
      date: '13 mai 2026',
      readingMin: 5,
      title: 'Crabos : les U18 en finale, et personne ne l\u2019a vu venir',
      lede: 'Victoire 24-19 face à Toulon dimanche. Trois joueurs surveillés de près par Patat. Le centre de formation respire.',
      tags: ['Crabos', 'Formation'],
      comments: 19,
    },
    {
      id: 'gorgadze-georgie',
      category: 'International',
      source: 'rugbyrama',
      author: 'Antoine Bertrand',
      time: 'hier',
      date: '13 mai 2026',
      readingMin: 3,
      title: 'Beka Gorgadze capitaine de la Géorgie : un Bayonnais sur le toit du Caucase',
      lede: 'Officialisation lundi. Première sélection en tant que capitaine prévue contre l\u2019Italie en juin. Fierté côté Pays Basque.',
      tags: ['Gorgadze', 'Géorgie'],
      comments: 22,
    },
    {
      id: 'derby-biarritz',
      category: 'Pays Basque',
      source: 'aupa',
      author: 'AUPA AB',
      time: 'il y a 2 j',
      date: '12 mai 2026',
      readingMin: 4,
      title: 'Derby : le BO en Pro D2 l\u2019an prochain. On peut en parler ?',
      lede: 'Le voisin va passer une dixième saison hors du Top 14. Personne, ici, n\u2019ose vraiment se réjouir. Personne ne va pleurer non plus.',
      tags: ['Biarritz', 'Derby'],
      comments: 187,
    },
    {
      id: 'billetterie-toulouse',
      category: 'Billetterie',
      source: 'sud-ouest',
      author: 'AB Communication',
      time: 'il y a 2 j',
      date: '12 mai 2026',
      readingMin: 2,
      title: 'Bayonne — Toulouse : 200 places remises en vente jeudi à 10h. Bonne chance.',
      lede: 'Désistements du parcage visiteur. La file d\u2019attente sera, comme d\u2019habitude, l\u2019occasion de se faire des amis.',
      tags: ['Billetterie'],
      comments: 8,
    },
    {
      id: 'umaga-rumeur',
      category: 'Coulisses',
      source: 'rmc',
      author: 'Mathieu Lartot',
      time: 'il y a 3 j',
      date: '11 mai 2026',
      readingMin: 4,
      title: 'Tana Umaga aperçu à Anglet : la rumeur qui ne meurt jamais',
      lede: 'L\u2019ancien All Black était au Pays Basque dimanche pour le mariage d\u2019un ami. Internet en a tiré les conclusions habituelles.',
      tags: ['Tana Umaga', 'Rumeurs', 'Internet'],
      comments: 144,
    },
    {
      id: 'patat-conf',
      category: 'Conférence',
      source: 'lequipe',
      author: 'Renaud Bourel',
      time: 'il y a 3 j',
      date: '11 mai 2026',
      readingMin: 3,
      title: 'Patat avant Toulouse : « On ne va pas leur faire un cadeau »',
      lede: 'Conférence de presse plus longue que prévue. L\u2019entraîneur a parlé du XV, de la mêlée, et — un peu — de Spedding.',
      tags: ['Grégory Patat', 'Conférence'],
      comments: 36,
    },
  ];

  // Comments for the featured article (Maka)
  const comments = [
    {
      id: 'c1',
      author: '@paco_pamplemousse',
      avatar: 'P',
      avatarBg: '#0B2545',
      role: 'MODÉRATEUR',
      time: 'il y a 12 min',
      body: 'Excellente nouvelle. Maka c\u2019est exactement le profil qu\u2019on doit garder : il joue dur, il ferme sa bouche, et il sort le grand match quand il faut. Bravo à la cellule sportive.',
      likes: 47,
      replies: [
        {
          id: 'c1r1',
          author: '@ttiki',
          avatar: 'T',
          avatarBg: '#0099D8',
          time: 'il y a 8 min',
          body: '@paco_pamplemousse +1. Et puis franchement, voir un type rester pour de bonnes raisons, ça change un peu.',
          likes: 12,
        },
      ],
    },
    {
      id: 'c2',
      author: '@maite_etxegoyen',
      avatar: 'M',
      avatarBg: '#D52B1E',
      role: 'CONTRIBUTRICE',
      time: 'il y a 28 min',
      body: 'Le passage sur l\u2019école bilingue d\u2019Anglet m\u2019a touchée. C\u2019est aussi pour ça qu\u2019on aime ce club : il ne signe pas que des contrats, il accueille des familles.',
      likes: 34,
      replies: [],
    },
    {
      id: 'c3',
      author: '@le_tonton_du_pignada',
      avatar: 'L',
      avatarBg: '#2F8F4F',
      time: 'il y a 41 min',
      body: 'Bon. Maintenant on prolonge Capilla et on en reparle.',
      likes: 89,
      replies: [
        {
          id: 'c3r1',
          author: '@dauger_forever',
          avatar: 'D',
          avatarBg: '#0B2545',
          time: 'il y a 32 min',
          body: 'On en parle TOUS les jours @le_tonton_du_pignada. Tous. Les. Jours.',
          likes: 24,
        },
        {
          id: 'c3r2',
          author: '@aldigé_oficiel_lol',
          avatar: 'A',
          avatarBg: '#5A6472',
          time: 'il y a 21 min',
          body: 'Patience, dossier complexe (signé : pas Aldigé)',
          likes: 56,
        },
      ],
    },
    {
      id: 'c4',
      author: '@txomin',
      avatar: 'T',
      avatarBg: '#0099D8',
      time: 'il y a 1 h',
      body: 'Deux saisons c\u2019est court. Pourquoi pas trois ? Question naïve d\u2019un abonné qui ne connaît rien aux contrats.',
      likes: 7,
      replies: [],
    },
    {
      id: 'c5',
      author: '@kanboko',
      avatar: 'K',
      avatarBg: '#D52B1E',
      time: 'il y a 1 h',
      body: '[Commentaire supprimé par son auteur]',
      deleted: true,
      replies: [],
    },
  ];

  const popularSearches = ['Spedding', 'Mercato 2026', 'Jean-Dauger', 'Tana Umaga', 'Top 14', 'Patat'];

  const trending = [
    { rank: 1, title: 'Mercato : les rumeurs de fin de saison, classées', id: 'rumeurs-classement' },
    { rank: 2, title: 'Edwin Maka prolonge deux saisons', id: 'maka-prolonge' },
    { rank: 3, title: 'Tana Umaga aperçu à Anglet', id: 'umaga-rumeur' },
    { rank: 4, title: 'Derby : le BO en Pro D2 l\u2019an prochain', id: 'derby-biarritz' },
    { rank: 5, title: 'Patat avant Toulouse : « On ne va pas leur faire un cadeau »', id: 'patat-conf' },
  ];

  const tribune = [
    { id: 't1', author: '@maite_etxegoyen', caption: 'Avant Castres, vue de la Sud — encore eux qui chantent en premier.' },
    { id: 't2', author: '@kanboko', caption: 'Mon fils, sa première écharpe. Ne dites rien à sa mère (supportrice du BO).' },
    { id: 't3', author: '@txomin', caption: '6h du matin, parking de Jean-Dauger. Les billets, c\u2019est sacré.' },
  ];

  return { sources, nextMatch, articles, comments, popularSearches, trending, tribune };
})();
